name: Sync Qase test cases to repo (8am Vancouver)

on:
  workflow_dispatch:
  # Fire hourly; only run the export at 08:00 local
  schedule:
    - cron: "0 * * * *"

concurrency:
  group: qase-sync
  cancel-in-progress: false

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      QASE_PROJECT_CODE: VERSEBYVER
      QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

    steps:
      - name: Determine local time (America/Vancouver)
        id: now
        shell: bash
        run: |
          HOUR=$(TZ=America/Vancouver date +%H)
          DATE=$(TZ=America/Vancouver date -Is)
          echo "hour=$HOUR" >> "$GITHUB_OUTPUT"
          echo "date=$DATE" >> "$GITHUB_OUTPUT"
          echo "Local time is $DATE"

      # Everything below only runs at 08:00 local time
      - name: Checkout
        if:
