name: Sync Qase test cases to repo (approx 8am Vancouver)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"  # 08:00 during PST (UTC-8)
    - cron: "0 15 * * *"  # 08:00 during PDT (UTC-7)

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      QASE_PROJECT_CODE: VERSEBYVER
      QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Preflight: env and API probe
        shell: bash
        run: |
          if [ -z "${QASE_API_TOKEN}" ]; then
            echo "::error::Missing secret QASE_API_TOKEN"; exit 2
          fi
          if [ -z "${QASE_PROJECT_CODE}" ]; then
            echo "::error::Missing env QASE_PROJECT_CODE"; exit 2
          fi
          URL="https://api.qase.io/v1/case/${QASE_PROJECT_CODE}?limit=1&offset=0"
          HTTP=$(curl -sS -o resp.json -w "%{http_code}" -H "X-Token: ${QASE_API_TOKEN}" "$URL")
          echo "Qase probe HTTP=$HTTP"
          if [ "$HTTP" -ne 200 ]; then
            echo "::error::Qase API returned HTTP $HTTP"
            cat resp.json
            exit 3
          fi

      - name: Export from Qase
        run: python scripts/qase_export.py

      - name: Commit changes
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add qase_export
          git commit -m "chore(qase): daily sync around 08:00 America/Vancouver" || echo "No changes"
          git push
